#! /bin/sh

case "$1" in
	start)
		echo "Loading scull driver..."
		scull_load
		echo "Loading faulty driver..."
		module_load faulty
		echo "Running modprobe on hello..."
		modprobe hello
		;;
	stop)
		echo "Unoading scull driver..."
		scull_unload
		echo "Loading faulty driver..."
		module_unload faulty
		echo "Running modprobe on hello..."
		rmmod hello
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
