#! /bin/sh

case "$1" in
	start)
		echo "Loading scull driver..."
		scull_load
		echo "Loading faulty driver..."
		module_load faulty
		echo "Running modprobe on hello..."
		modprobe hello
		echo "Loading aesdchar..."
		aesdchar_load
		;;
	stop)
		echo "Unoading aesdchar..."
		aesdchar_unload
		echo "Remove modprobe on hello..."
		rmmod hello
		echo "Unloading faulty driver..."
		module_unload faulty
		echo "Unoading scull driver..."
		scull_unload
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
